"""empty message

Revision ID: 5dd24cb856fd
Revises: 9ed210744036
Create Date: 2019-08-13 14:58:55.854917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd24cb856fd'
down_revision = '9ed210744036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author'], ['id'])
    op.drop_column('posts', 'first_name')
    op.drop_column('posts', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('last_name', sa.VARCHAR(length=30), nullable=False))
    op.add_column('posts', sa.Column('first_name', sa.VARCHAR(length=30), nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author')
    op.drop_table('users')
    # ### end Alembic commands ###
